# Travis CI Config
sudo: required
dist: xenial
language: generic

notifications:
  email:
    recipients:
      - maintainers@uwreact.ca
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:
    # Use StereoLabs' Docker image to avoid having to manually download
    # and install CUDA and the ZED SDK
    - DOCKER_BASE_IMAGE="stereolabs/zed:ubuntu1804-cuda10.0-zed2.7"

    # Install non-distributed dependencies
    - UPSTREAM_WORKSPACE="file"
    - ROSINSTALL_FILENAME="uwreact_robot.rosinstall"

    # Run clang_format
    - CLANG_FORMAT_CHECK="file"
    - CLANG_FORMAT_VERSION="7"
  matrix:
    - ROS_DISTRO="melodic"   ROS_REPO="ros"
    - ROS_DISTRO="melodic"   ROS_REPO="ros-shadow-fixed"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
