# Travis CI Config
sudo: required
dist: xenial
language: generic

notifications:
  email: false
  # TODO(matthew-reynolds): Branch-specific notifications. See #75

env:
  global:
    # Use StereoLabs' Docker image to avoid having to manually download
    # and install CUDA and the ZED SDK
    - DOCKER_BASE_IMAGE="stereolabs/zed:ubuntu1804-cuda10.0-zed2.8"

    # Install non-distributed dependencies
    - UPSTREAM_WORKSPACE="file"
    - ROSINSTALL_FILENAME="uwreact_robot.rosinstall"

    # Run linters and style checks
    - CATKIN_CONFIG='-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
    - AFTER_SCRIPT="cd /root/catkin_ws/src/uwreact_robot; ./run_linters.py"
  matrix:
    - ROS_DISTRO="melodic"   ROS_REPO="ros"
    - ROS_DISTRO="melodic"   ROS_REPO="ros-testing"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
